#! /bin/bash

#./ellesmere < fib.el 2>stderr.out 3>program.out 4>interpreter.out 5>&4 6>parserGenTrace.out

WHICH=${1:-default}
if [ -n "$1" ]; then
	export EL_optLimit="$WHICH"
fi
shift

./ellesmere < fib.el 3>$WHICH.out 4>&3 5>&3 6>&3
